routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/crud/pessoas');
});

Route::prefix('crud')->group(function(){
    Route::resource('pessoas', 'PeopleController');
});

app/Models/Person.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

/**
 * Class Person.
 *
 * @package namespace App\Models;
 */
class Person extends Model implements Transformable
{
    use TransformableTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'cpf', 'phone_number'];

}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PeopleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use Prettus\Validator\Contracts\ValidatorInterface;
use Prettus\Validator\Exceptions\ValidatorException;
use App\Http\Requests\PersonCreateRequest;
use App\Http\Requests\PersonUpdateRequest;
use App\Repositories\PersonRepository;
use App\Validators\PersonValidator;


class PeopleController extends Controller
{
    
    protected $repository;

    protected $validator;

    public function __construct(PersonRepository $repository, PersonValidator $validator)
    {
        $this->repository = $repository;
        $this->validator  = $validator;
    }

    public function index()
    {
        $this->repository->pushCriteria(app('Prettus\Repository\Criteria\RequestCriteria'));
        $people = $this->repository->orderBy('id', 'desc')->get();

        if (request()->wantsJson()) {

            foreach( $people as $person )
            {
                $person->actions = '<div class="text-right">
                <button type="button" class="btn btn-xs btn-warning" onclick="editPerson('.$person->id.')">
                <i class="fa fa-fw fa-edit"></i> editar
                </button>
                <button type="button" class="btn btn-xs btn-danger" onclick="deletePerson('.$person->id.')">
                <i class="fa fa-fw fa-trash"></i> deletar
                </button>
                </div>';    
            }

            return response()->json([
                'data' => $people,
            ]);
        }

        return view('people.index', compact('people'));
    }

    public function store(PersonCreateRequest $request)
    {
        try {

            $this->validator->with($request->all())->passesOrFail(ValidatorInterface::RULE_CREATE);

            $person = $this->repository->create($request->all());

            $response = [
                'message' => 'Person created.',
                'data'    => $person->toArray(),
            ];

            if ($request->wantsJson()) {

                return response()->json($response);
            }

            return redirect()->back()->with('message', $response['message']);
        } catch (ValidatorException $e) {
            if ($request->wantsJson()) {
                return response()->json([
                    'error'   => true,
                    'message' => $e->getMessageBag()
                ]);
            }

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }

    public function show($id)
    {
        $person = $this->repository->find($id);

        return response()->json([
            'data' => $person,
        ]);
    }

    public function edit($id)
    {
        $person = $this->repository->find($id);

        return view('people.edit', compact('person'));
    }

    public function update(PersonUpdateRequest $request, $id)
    {
        try {

            $this->validator->with($request->all())->passesOrFail(ValidatorInterface::RULE_UPDATE);

            $person = $this->repository->update($request->all(), $id);

            $response = [
                'message' => 'Person updated.',
                'data'    => $person->toArray(),
            ];

            if ($request->wantsJson()) {

                return response()->json($response);
            }

            return redirect()->back()->with('message', $response['message']);
        } catch (ValidatorException $e) {

            if ($request->wantsJson()) {

                return response()->json([
                    'error'   => true,
                    'message' => $e->getMessageBag()
                ]);
            }

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }

    public function destroy($id)
    {
        $deleted = $this->repository->delete($id);

        if (request()->wantsJson()) {

            return response()->json([
                'message' => 'Person deleted.',
                'deleted' => $deleted,
            ]);
        }

        return redirect()->back()->with('message', 'Person deleted.');
    }
}

resources/views/layouts/base.blade.php
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
            crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap4.min.css">
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <title>CRUD TESTE!</title>
    </head>

    <body>
        <main class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="card">
                        <div class="card-body main-content">
                            @yield('content')
                        </div>
                    </div>
                </div>
            </div>
        </main>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
            crossorigin="anonymous"></script>
        <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
        <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
        <script src="{{ asset('js/app.js') }}"></script>
    </body>
</html>

resources/views/people/includes/add.blade.php
<div class="box box-solid">
    <div class="box-body">
        <form action="{{ route('pessoas.store') }}" method="POST">
        {{ csrf_field() }}
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="name">Nome</label>
                        <input class="form-control" name="name" placeholder="Digite um nome" requied>
                    </div>
                </div>
            

                <div class="col-sm-2">
                    <div class="form-group">
                        <label for="cpf">CPF</label>
                        <input class="form-control" name="cpf" placeholder="000.000.000-00" required>
                    </div>
                </div>
                
                <div class="col-sm-2">
                    <div class="form-group">
                        <label for="phone_number">Telefone</label>
                        <input class="form-control" name="phone_number" placeholder="(00) 00000-0000)" required>
                    </div>
                </div>

                <div class="col-sm-2">
                    <button 
                        type="submit" 
                        class="btn btn-block btn-primary"
                        style="margin-top: 1.8em;"
                    >
                        Adicionar
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>

resources/views/people/includes/delete_form.blade.php
<form id="form-delete-person" method="POST">
    {{ csrf_field() }}
    {{ method_field('DELETE') }}
</form>

resources/views/people/includes/edit.blade.php
<!-- Modal -->
<div class="modal fade" id="modal-edit-person" tabindex="-1" role="dialog" aria-labelledby="modal-edit-personLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="modal-edit-personLabel"></h4>
            </div>
            <form id="form-edit-person" method="POST">
                <div class="modal-body">
                    {{ csrf_field() }}
                    {{ method_field('PUT') }}
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="name">Nome</label>
                                    <input class="form-control" name="name" placeholder="Digite um nome">
                                </div>
                            </div>
                        

                            <div class="col-sm-3">
                                <div class="form-group">
                                    <label for="cpf">CPF</label>
                                    <input class="form-control" name="cpf" placeholder="000.000.000-00">
                                </div>
                            </div>
                            
                            <div class="col-sm-3">
                                <div class="form-group">
                                    <label for="phone_number">Telefone</label>
                                    <input class="form-control" name="phone_number" placeholder="(00) 00000-0000" required>
                                </div>
                            </div>

                        </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-primary">Salvar alterações</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/people/index.blade.php
@extends('adminlte::page') 

@section('CRUD Pessoa', 'Dashboard') 

@section('content')

<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        @include('people.includes.add')

        <div class="box box-solid">
            <div class="box-body">
                <div class="table-responsive">
                    <table class="table table condensed" id="people-table">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Nome</th>
                                <th>CPF</th>
                                <th>Telefone</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach( $people as $person )
                                <tr>
                                    <td>{{ $person->id }}</td>
                                    <td>{{ $person->name }}</td>
                                    <td>{{ $person->cpf }}</td>
                                    <td>{{ $person->phone_number }}</td>
                                    <td class="text-right" width="190px;">
                                        <div class="text-right">
                                            <button 
                                                id="edit-button-{{ $person->id }}"
                                                type="button" 
                                                class="btn btn-xs btn-warning" 
                                                onclick="editPerson({{ $person->id }})"
                                                data-loading-text='<i class="fa fa-fw fa-spinner"></i> Carregando ...'
                                            >
                                                <i class="fa fa-fw fa-edit"></i> editar
                                            </button>

                                            <button 
                                                type="button" 
                                                class="btn btn-xs btn-danger" 
                                                onclick="deletePerson({{$person->id}})"
                                            >
                                                <i class="fa fa-fw fa-trash"></i> deletar
                                            </button>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@include('people.includes.edit')
@include('people.includes.delete_form')
@stop

@section('js')
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="{{ asset('js/app.js') }}"></script>
@stop